version: '3.2'
services:
  db:
    image: postgres:15-alpine
    container_name: megano_shop_database
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data
