# Generated by Django 4.1.3 on 2023-01-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_megano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='app_megano.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=models.ManyToManyField(related_name='details', to='app_megano.detail', verbose_name='детали'),
        ),
        migrations.AddField(
            model_name='goods',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='app_megano.tags', verbose_name='тэг'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_megano.goods', verbose_name='Фото'),
        ),
        migrations.AlterUniqueTogether(
            name='detail',
            unique_together={('type', 'info')},
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_megano.goods', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_megano.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
