# Generated by Django 4.1.3 on 2023-02-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0006_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('valid_from',), 'verbose_name': 'скидка', 'verbose_name_plural': 'скидки'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_megano.goods', verbose_name='Товар'),
        ),
    ]
