# Generated by Django 4.1.3 on 2023-03-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0009_alter_comment_options_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_comment',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
