# Generated by Django 4.1.3 on 2023-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_megano", "0014_alter_detail_info_alter_detail_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="category",
        ),
        migrations.AlterField(
            model_name="goods",
            name="name",
            field=models.TextField(max_length=200, verbose_name="Название"),
        ),
    ]
