# Generated by Django 4.1.3 on 2023-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_order',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный заказ'),
        ),
    ]
