# Generated by Django 4.1.3 on 2022-12-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
                ('icon', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Иконка')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранная')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('image', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Картинка')),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_megano.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='Тип')),
                ('info', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'детали',
                'verbose_name_plural': 'детали',
                'unique_together': {('type', 'info')},
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/images/', verbose_name='Основная фотография')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='Ограниченная серия')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ManyToManyField(related_name='categories', to='app_megano.category', verbose_name='Категория')),
                ('detail', models.ManyToManyField(related_name='details', to='app_megano.detail', verbose_name='детали')),
                ('tag', models.ManyToManyField(related_name='tags', to='app_megano.tags', verbose_name='тэг')),
                ('views', models.ManyToManyField(blank=True, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('-date_create',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_megano.goods', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'еще фотография',
                'verbose_name_plural': 'добавить фотографий',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_megano.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
