# Generated by Django 4.1.3 on 2022-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0003_viewedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
