# Generated by Django 4.1.3 on 2023-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0004_purchases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Теги'),
        ),
    ]
