# Generated by Django 4.1.3 on 2023-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0013_alter_comment_active_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='info',
            field=models.CharField(max_length=200, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='type',
            field=models.CharField(max_length=40, verbose_name='Название атрибута'),
        ),
    ]
